#pragma once
// AUTO-GENERATED by tools/config_codegen.py --emit-constants from ConfigSchema.json. DO NOT EDIT.
//
// Shared config-mirrored constants (  / ). Each value is the
// config DEFAULT for the named param, emitted ONCE here so the C++ consumer and the
// config schema cannot hand-duplicate-and-drift. Regenerate via tools/config_codegen.py
// --emit-constants; tools/config_codegen.py --check-constants fails CI if this is stale.
//
// The shader-side twin is emitted to res/shaders/config_constants.gen.glsl
// from the same table and is validated by --check-constants.

#include <glm/glm.hpp>

namespace luminumbra::core::config_constants {

// RenderMoonlight.strength — config default (scalar).
inline constexpr float kMoonlightStrength = 0.0f;

// RenderMoonlight.color — config default (vec3); components exposed as
// scalars for the shader-side twin and a compile-safe fallback.
inline constexpr float kMoonlightColorR = 0.6f;
inline constexpr float kMoonlightColorG = 0.7f;
inline constexpr float kMoonlightColorB = 1.0f;
inline constexpr glm::vec3 kMoonlightColor =
    glm::vec3(kMoonlightColorR, kMoonlightColorG, kMoonlightColorB);

} // namespace luminumbra::core::config_constants
