#pragma once
// AUTO-GENERATED by tools/config_codegen.py --emit-constants from ConfigSchema.json. DO NOT EDIT.
//
// Shared config-mirrored constants (spec 020 FR-B-007 / OPS-08). Each value is the
// config DEFAULT for the named param, emitted ONCE here so the C++ consumer and the
// config schema cannot hand-duplicate-and-drift. Regenerate via tools/config_codegen.py
// --emit-constants; tools/config_codegen.py --check-constants fails CI if this is stale.
//
// Shader-side twin (TODO when the shader consumer migrates): emit the SAME defaults
// into a generated GLSL/Slang include from this same table, e.g.
//   #define LUMIN_MOONLIGHT_STRENGTH 0.0
//   #define LUMIN_MOONLIGHT_COLOR vec3(0.6, 0.7, 1.0)
// keeping the numbers sourced from ConfigSchema.json (never hand-typed in a shader).

#include <glm/glm.hpp>

namespace luminumbra::core::config_constants {

// RenderMoonlight.strength — config default (scalar).
inline constexpr float kMoonlightStrength = 0.0f;

// RenderMoonlight.color — config default (vec3); components exposed as
// scalars for the shader-side twin and a compile-safe fallback.
inline constexpr float kMoonlightColorR = 0.6f;
inline constexpr float kMoonlightColorG = 0.7f;
inline constexpr float kMoonlightColorB = 1.0f;
inline constexpr glm::vec3 kMoonlightColor = glm::vec3(kMoonlightColorR, kMoonlightColorG, kMoonlightColorB);

}  // namespace luminumbra::core::config_constants

