#pragma once
// AUTO-GENERATED by tools/config_codegen.py from ConfigSchema.json. DO NOT EDIT.
//
// Behavior-neutral registry: byte-faithful to the hand-written kKeys/kParams
// tables in SystemConfig.cpp. Residency is schema-declared: KEY() rows carry
// 'hashed' (sim, folded into config:v1:) or 'excluded' (render, never hashed).
//
// X-macro tables: SystemConfig.h expands LUMIN_CONFIG_KEY_TABLE/PARAM_TABLE to
// generate the SysKey/SysParam enums, and SystemConfig.cpp expands them to build
// the kKeys/kParams registries, so the parallel arrays have ONE authored home
// (ConfigSchema.json) and cannot drift. Regenerate via tools/config_codegen.py
// --emit; tools/config_codegen.py --check fails CI if this file is stale.

// Codegen owns these bytes: the configure-time drift check enforces
// byte-freshness against the emitter, so clang-format must not re-wrap
// the X-macro continuation lines.
// clang-format off
// KEY(enum, Section, "json_section", "json_name", residency)
#define LUMIN_CONFIG_KEY_TABLE(KEY) \
  KEY(SimPlantGrowth, Sim, "sim", "plant_growth", hashed) \
  KEY(SimErosion, Sim, "sim", "erosion", hashed) \
  KEY(SimEcology, Sim, "sim", "ecology", hashed) \
  KEY(SimWildlifeFoliage, Sim, "sim", "wildlife_foliage", hashed) \
  KEY(SimThirst, Sim, "sim", "thirst", hashed) \
  KEY(SimScavenging, Sim, "sim", "scavenging", hashed) \
  KEY(SimReproduction, Sim, "sim", "reproduction", hashed) \
  KEY(SimForaging, Sim, "sim", "foraging", hashed) \
  KEY(SimHydrologyWeather, Sim, "sim", "hydrology_weather", hashed) \
  KEY(SimWeatherEvents, Sim, "sim", "weather_events", hashed) \
  KEY(SimAetherState, Sim, "sim", "aether_state", hashed) \
  KEY(SimWaterHighRes, Sim, "sim", "water_high_res", hashed) \
  KEY(RenderMoonlight, Render, "render", "moonlight", excluded) \
  KEY(RenderTreeWind, Render, "render", "tree_wind", excluded) \
  KEY(RenderPlantProcgen, Render, "render", "plant_procgen", excluded) \
  KEY(RenderTaau, Render, "render", "taau", excluded) \
  KEY(RenderSkyLutGpu, Render, "render", "sky_lut_gpu", excluded) \
  KEY(RenderCircadian, Render, "render", "circadian", excluded) \
  KEY(RenderCreatureSpawn, Render, "render", "creature_spawn", excluded) \
  KEY(RenderForagingColony, Render, "render", "foraging_colony", excluded) \
  KEY(RenderLiveWeather, Render, "render", "live_weather", excluded) \
  KEY(RenderAetherTap, Render, "render", "aether_tap", excluded) \
  KEY(RenderSnowCover, Render, "render", "snow_cover", excluded)

// PARAM(enum, owner, "json_name", is_vec3, default_scalar, vx, vy, vz)
#define LUMIN_CONFIG_PARAM_TABLE(PARAM) \
  PARAM(PlantMutationRate, SimPlantGrowth, "mutation_rate", false, 0.05f, 0.0f, 0.0f, 0.0f) \
  PARAM(MoonlightStrength, RenderMoonlight, "strength", false, 0.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(MoonlightColor, RenderMoonlight, "color", true, 0.0f, 0.6f, 0.7f, 1.0f) \
  PARAM(EcoEnergyDrain, SimEcology, "energy_drain_per_second", false, 0.006f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoEnergyRestRecover, SimEcology, "energy_rest_recover", false, 0.08f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoEnergySleepRecover, SimEcology, "energy_sleep_recover", false, 0.16f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoHungerGrowth, SimEcology, "hunger_growth_per_second", false, 0.02f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoHungerGrazeSate, SimEcology, "hunger_graze_sate", false, 0.5f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoStaminaRestRecover, SimEcology, "stamina_rest_recover", false, 0.3f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoStaminaMoveDrain, SimEcology, "stamina_move_drain", false, 0.1f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoHerdWeight, SimEcology, "herd_weight", false, 0.8f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoAlignmentWeight, SimEcology, "alignment_weight", false, 0.5f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoCatchRadius, SimEcology, "catch_radius", false, 2.2f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoCatchSatiation, SimEcology, "catch_satiation", false, 0.8f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoFlockNeighborRadius, SimEcology, "flock_neighbor_radius", false, 12.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoFlockSeparationRadius, SimEcology, "flock_separation_radius", false, 3.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoFlockCohesionWeight, SimEcology, "flock_cohesion_weight", false, 0.6f, 0.0f, 0.0f, 0.0f) \
  PARAM(EcoFlockSeparationWeight, SimEcology, "flock_separation_weight", false, 1.4f, 0.0f, 0.0f, 0.0f) \
  PARAM(WfGrazeRadius, SimWildlifeFoliage, "graze_radius", false, 3.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(WfGrazePerCreature, SimWildlifeFoliage, "graze_per_creature", false, 0.05f, 0.0f, 0.0f, 0.0f) \
  PARAM(WfRegrowPerTick, SimWildlifeFoliage, "regrow_per_tick", false, 0.01f, 0.0f, 0.0f, 0.0f) \
  PARAM(WfFeedPerGraze, SimWildlifeFoliage, "feed_per_graze", false, 0.02f, 0.0f, 0.0f, 0.0f) \
  PARAM(ThirstRiseRate, SimThirst, "rise_rate_per_second", false, 0.04f, 0.0f, 0.0f, 0.0f) \
  PARAM(ThirstDrinkRate, SimThirst, "drink_rate_per_second", false, 0.5f, 0.0f, 0.0f, 0.0f) \
  PARAM(ThirstSeekThreshold, SimThirst, "seek_threshold", false, 0.3f, 0.0f, 0.0f, 0.0f) \
  PARAM(ScavHungerThreshold, SimScavenging, "hunger_threshold", false, 0.3f, 0.0f, 0.0f, 0.0f) \
  PARAM(ScavFeedRadius, SimScavenging, "feed_radius", false, 1.5f, 0.0f, 0.0f, 0.0f) \
  PARAM(ScavFeedRate, SimScavenging, "feed_rate_per_tick", false, 0.05f, 0.0f, 0.0f, 0.0f) \
  PARAM(ReproMaturityTicks, SimReproduction, "maturity_ticks", false, 90.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(ReproCooldownTicks, SimReproduction, "cooldown_ticks", false, 300.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(ReproHealthyStamina, SimReproduction, "healthy_stamina", false, 0.5f, 0.0f, 0.0f, 0.0f) \
  PARAM(ReproMateSeekRadius, SimReproduction, "mate_seek_radius", false, 45.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(ReproCourtshipRadius, SimReproduction, "courtship_radius", false, 2.6f, 0.0f, 0.0f, 0.0f) \
  PARAM(ReproCourtshipTicks, SimReproduction, "courtship_ticks", false, 90.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(ReproSpawnRadius, SimReproduction, "spawn_radius", false, 1.2f, 0.0f, 0.0f, 0.0f) \
  PARAM(ForagingDeposit, SimForaging, "deposit", false, 1.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(ForagingTrailWeight, SimForaging, "trail_weight", false, 8.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(ForagingGoalWeight, SimForaging, "goal_weight", false, 1.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(CircadianAmplitude, RenderCircadian, "amplitude", false, 1.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(SpawnHerdCount, RenderCreatureSpawn, "herd_count", false, 12.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(SpawnPredatorSpeed, RenderCreatureSpawn, "predator_speed", false, 4.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(SpawnPreySpeed, RenderCreatureSpawn, "prey_speed", false, 2.6f, 0.0f, 0.0f, 0.0f) \
  PARAM(SpawnInitialHunger, RenderCreatureSpawn, "initial_hunger", false, 0.2f, 0.0f, 0.0f, 0.0f) \
  PARAM(ColonyAntCount, RenderForagingColony, "ant_count", false, 24.0f, 0.0f, 0.0f, 0.0f) \
  PARAM(ColonyFoodAmount, RenderForagingColony, "food_amount", false, 1000000.0f, 0.0f, 0.0f, 0.0f)
// clang-format on
