#include "core/SystemConfig.h"

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <sstream>

#include "core/Environment.h"
#include "nlohmann/json.hpp"
#include "persistence/WorldPersistenceRoundtrip.h" // Luminumbra::Persistence::StableChecksum

namespace luminumbra::core {
namespace {

enum class Section : std::uint8_t {
    Sim,
    Render
};

struct KeyMeta {
    SysKey key;
    Section section;
    const char* json_section; // "sim" | "render"
    const char* json_name;    // e.g. "plant_growth"
};

struct ParamMeta {
    SysParam id;
    SysKey owner;
    const char* json_name; // e.g. "mutation_rate"
    bool is_vec3;
    float default_scalar;
    glm::vec3 default_vec3;
};

// Canonical registry. Order is the hash's canonical order; keep sim.* keys grouped.
// GENERATED by expanding the X-macro tables in SystemConfigRegistry.gen.h (pulled in via
// SystemConfig.h), whose single authored home is ConfigSchema.json. The expanded KeyMeta /
// ParamMeta field values are byte-identical to the prior hand-written arrays, so
// ComputeConfigSubHash emits a character-for-character identical config:v1: string. Do NOT
// edit these tables by hand — edit ConfigSchema.json then `python tools/config_codegen.py
// --emit src/luminumbra_common/core/SystemConfigRegistry.gen.h`; --check fails CI on drift.
constexpr KeyMeta kKeys[] = {
#define LUMIN_CONFIG_EMIT_KEY(ENUM, SECTION, JSON_SECTION, JSON_NAME, RESIDENCY)                   \
    {SysKey::ENUM, Section::SECTION, JSON_SECTION, JSON_NAME},
    LUMIN_CONFIG_KEY_TABLE(LUMIN_CONFIG_EMIT_KEY)
#undef LUMIN_CONFIG_EMIT_KEY
};

constexpr ParamMeta kParams[] = {
#define LUMIN_CONFIG_EMIT_PARAM(ENUM, OWNER, JSON_NAME, IS_VEC3, SCALAR, VX, VY, VZ)               \
    {SysParam::ENUM, SysKey::OWNER, JSON_NAME, IS_VEC3, SCALAR, glm::vec3(VX, VY, VZ)},
    LUMIN_CONFIG_PARAM_TABLE(LUMIN_CONFIG_EMIT_PARAM)
#undef LUMIN_CONFIG_EMIT_PARAM
};

// Overlay the `user.*` section of `data` onto `user`, setting only named fields (merge
// semantics: an absent field keeps its current/default value). render-client-only; never hashed.
void ParseUserSection(const nlohmann::json& data, UserSettings& user) {
    if (!data.is_object() || !data.contains("user") || !data["user"].is_object())
        return;
    const nlohmann::json& u = data["user"];

    if (u.contains("video") && u["video"].is_object()) {
        const nlohmann::json& v = u["video"];
        if (v.contains("resolution") && v["resolution"].is_string())
            user.resolution = v["resolution"].get<std::string>();
        if (v.contains("window_mode") && v["window_mode"].is_string())
            user.window_mode = v["window_mode"].get<std::string>();
        if (v.contains("vsync") && v["vsync"].is_boolean())
            user.vsync = v["vsync"].get<bool>();
        if (v.contains("fov") && v["fov"].is_number())
            user.fov = v["fov"].get<float>();
        if (v.contains("render_scale") && v["render_scale"].is_number())
            user.render_scale = v["render_scale"].get<float>();
        if (v.contains("ui_scale") && v["ui_scale"].is_number())
            user.ui_scale = v["ui_scale"].get<float>();
        if (v.contains("mouse_sensitivity") && v["mouse_sensitivity"].is_number())
            user.mouse_sensitivity = v["mouse_sensitivity"].get<float>();
    }
    if (u.contains("audio") && u["audio"].is_object()) {
        const nlohmann::json& a = u["audio"];
        if (a.contains("master") && a["master"].is_number())
            user.audio_master = a["master"].get<float>();
        if (a.contains("sfx") && a["sfx"].is_number())
            user.audio_sfx = a["sfx"].get<float>();
        if (a.contains("music") && a["music"].is_number())
            user.audio_music = a["music"].get<float>();
    }
    if (u.contains("controls") && u["controls"].is_object()) {
        for (const auto& [action, key] : u["controls"].items()) {
            if (key.is_number_integer())
                user.keybinds[action] = key.get<int>();
        }
    }
}

} // namespace

SystemConfig SystemConfig::Defaults() {
    return SystemConfig{};
}

SystemConfig SystemConfig::FromJsonString(const std::string& json_text) {
    SystemConfig cfg; // start from all-defaults; overlay only what the JSON names

    nlohmann::json data;
    try {
        data = nlohmann::json::parse(json_text);
    } catch (const nlohmann::json::parse_error&) {
        return cfg; // malformed/empty/blank -> defaults (graceful)
    }
    if (!data.is_object())
        return cfg;

    for (const auto& key_meta : kKeys) {
        if (!data.contains(key_meta.json_section))
            continue;
        const nlohmann::json& section = data[key_meta.json_section];
        if (!section.is_object() || !section.contains(key_meta.json_name))
            continue;
        const nlohmann::json& entry = section[key_meta.json_name];
        if (!entry.is_object())
            continue;

        if (entry.contains("enabled") && entry["enabled"].is_boolean() &&
            entry["enabled"].get<bool>()) {
            cfg.m_enabled |= (1u << static_cast<unsigned>(key_meta.key));
        }

        if (!entry.contains("params") || !entry["params"].is_object())
            continue;
        const nlohmann::json& params = entry["params"];
        for (const auto& pm : kParams) {
            if (pm.owner != key_meta.key)
                continue;
            if (!params.contains(pm.json_name))
                continue;
            const nlohmann::json& value = params[pm.json_name];
            const std::size_t pi = static_cast<std::size_t>(pm.id);
            if (pm.is_vec3) {
                if (value.is_array() && value.size() == 3) {
                    cfg.m_params[pi] = glm::vec3(
                        value[0].get<float>(), value[1].get<float>(), value[2].get<float>());
                    cfg.m_param_set |= (1ull << static_cast<unsigned>(pm.id));
                }
            } else if (value.is_number()) {
                cfg.m_params[pi].x = value.get<float>();
                cfg.m_param_set |= (1ull << static_cast<unsigned>(pm.id));
            }
        }
    }

    ParseUserSection(data, cfg.m_user); // user.* (client-only, never hashed)
    return cfg;
}

SystemConfig SystemConfig::LoadFromFile(const std::string& path) {
    std::ifstream file(path);
    if (!file)
        return SystemConfig{}; // missing/unreadable -> defaults
    std::ostringstream buffer;
    buffer << file.rdbuf();
    return FromJsonString(buffer.str());
}

float SystemConfig::param(SysParam id, float fallback) const {
    if ((m_param_set >> static_cast<unsigned>(id)) & 1u) {
        return m_params[static_cast<std::size_t>(id)].x;
    }
    return fallback;
}

glm::vec3 SystemConfig::param3(SysParam id, glm::vec3 fallback) const {
    if ((m_param_set >> static_cast<unsigned>(id)) & 1u) {
        return m_params[static_cast<std::size_t>(id)];
    }
    return fallback;
}

std::string SystemConfig::ComputeConfigSubHash() const {
    std::ostringstream bytes;
    bytes << "config:v1:" << std::setprecision(17);
    bool any = false;

    for (const auto& key_meta : kKeys) {
        if (key_meta.section != Section::Sim)
            continue; // render.* never hashed
        if (!enabled(key_meta.key))
            continue; // only enabled sim systems affect state
        any = true;
        bytes << key_meta.json_name << ":en=1;";
        // Emit every owned param's RESOLVED value (set value or compiled default), in
        // SysParam enum order, so identical configs hash identically regardless of JSON order.
        for (const auto& pm : kParams) {
            if (pm.owner != key_meta.key)
                continue;
            const std::size_t pi = static_cast<std::size_t>(pm.id);
            const bool set = (m_param_set >> static_cast<unsigned>(pm.id)) & 1u;
            if (pm.is_vec3) {
                const glm::vec3 v = set ? m_params[pi] : pm.default_vec3;
                bytes << pm.json_name << '=' << v.x << ',' << v.y << ',' << v.z << ';';
            } else {
                const float v = set ? m_params[pi].x : pm.default_scalar;
                bytes << pm.json_name << '=' << v << ';';
            }
        }
    }

    if (!any)
        return {}; // all sim defaults -> byte-identical baseline
    return Luminumbra::Persistence::StableChecksum(bytes.str());
}

int SystemConfig::keybind(const std::string& action, int fallback) const {
    const auto it = m_user.keybinds.find(action);
    return it != m_user.keybinds.end() ? it->second : fallback;
}

void SystemConfig::OverlayUserFromJsonString(const std::string& json_text) {
    nlohmann::json data;
    try {
        data = nlohmann::json::parse(json_text);
    } catch (const nlohmann::json::parse_error&) {
        return; // malformed overlay -> leave settings unchanged
    }
    ParseUserSection(data, m_user); // only user.*; sim/render ignored
}

SystemConfig SystemConfig::LoadLayered(const std::string& defaults_path,
                                       const std::string& overlay_path) {
    SystemConfig cfg =
        LoadFromFile(defaults_path); // sim/render/user from defaults (missing -> defaults)
    std::ifstream overlay(overlay_path);
    if (overlay) {
        std::ostringstream buffer;
        buffer << overlay.rdbuf();
        cfg.OverlayUserFromJsonString(buffer.str()); // per-user file overrides only user.*
    }
    return cfg;
}

bool SystemConfig::SaveUserOverlay(const std::string& path) const {
    // Serialize ONLY the user.* section (no sim/render leakage). Ordered keybinds -> deterministic.
    nlohmann::json user;
    user["video"] = {
        {"resolution", m_user.resolution},
        {"window_mode", m_user.window_mode},
        {"vsync", m_user.vsync},
        {"fov", m_user.fov},
        {"render_scale", m_user.render_scale},
        {"ui_scale", m_user.ui_scale},
        {"mouse_sensitivity", m_user.mouse_sensitivity},
    };
    user["audio"] = {
        {"master", m_user.audio_master},
        {"sfx", m_user.audio_sfx},
        {"music", m_user.audio_music},
    };
    nlohmann::json controls = nlohmann::json::object();
    for (const auto& [action, key] : m_user.keybinds)
        controls[action] = key;
    user["controls"] = controls;

    nlohmann::json doc;
    doc["_comment"] =
        "Luminumbra per-user settings overlay (user.* only; client-only, never hashed).";
    doc["user"] = user;

    std::error_code ec;
    const std::filesystem::path out(path);
    if (out.has_parent_path())
        std::filesystem::create_directories(out.parent_path(), ec);

    // Atomic-ish write: temp file then rename over the target.
    const std::filesystem::path tmp = out.string() + ".tmp";
    {
        std::ofstream file(tmp, std::ios::binary | std::ios::trunc);
        if (!file)
            return false;
        file << doc.dump(2) << '\n';
        if (!file)
            return false;
    }
    std::filesystem::rename(tmp, out, ec);
    if (ec) {
        std::filesystem::remove(tmp, ec);
        return false;
    }
    return true;
}

std::string SystemConfig::DefaultUserOverlayPath() {
#if defined(_WIN32)
    if (const auto appdata = Luminumbra::Core::ReadEnvironment("APPDATA")) {
        return (std::filesystem::path(*appdata) / "Luminumbra" / "settings.json").string();
    }
#else
    if (const auto xdg = Luminumbra::Core::ReadEnvironment("XDG_CONFIG_HOME")) {
        return (std::filesystem::path(*xdg) / "luminumbra" / "settings.json").string();
    }
    if (const auto home = Luminumbra::Core::ReadEnvironment("HOME")) {
        return (std::filesystem::path(*home) / ".config" / "luminumbra" / "settings.json").string();
    }
#endif
    return "settings.json"; // last-resort: cwd
}

} // namespace luminumbra::core
