#!/usr/bin/env python3
"""Generate the embedded GGX environment BRDF table using only the standard library.

Model: GGX NDF, Schlick Fresnel, Schlick-Smith IBL visibility (k=roughness^2/2).
Split-sum integration follows Karis, Real Shading in Unreal Engine 4 (2013):
https://cdn2.unrealengine.com/Resources/files/2013SiggraphPresentationsNotes-26915738.pdf
No game state/content or third-party asset is an input. Output is RG16F, no mipmaps.
"""

import argparse
import math
from pathlib import Path
import struct


SIZE = 64
SAMPLES = 2048
OUTPUT = Path(__file__).resolve().parents[2] / "src/luminumbra_client/rendering/EnvironmentBrdfLut.gen.h"


def generate():
    samples = []
    for index in range(SAMPLES):
        # Base-2 radical inverse of the fixed 11-bit Hammersley index.
        inverse = int(f"{index:011b}"[::-1], 2) / SAMPLES
        phi = 2 * math.pi * index / SAMPLES
        samples.append((inverse, math.cos(phi)))
    table = []
    for y in range(SIZE):
        roughness = 0.05 + 0.95 * y / (SIZE - 1)
        alpha2 = roughness**4
        k = roughness**2 / 2
        half_vectors = []
        for inverse, cosine in samples:
            hz = math.sqrt((1 - inverse) / (1 + (alpha2 - 1) * inverse))
            hx = math.sqrt(max(0, 1 - hz * hz)) * cosine
            half_vectors.append((hx, hz))
        for x in range(SIZE):
            ndv = (x / (SIZE - 1)) ** 2
            vx = math.sqrt(max(0, 1 - ndv * ndv))
            scale = bias = 0.0
            for hx, hz in half_vectors:
                vdh = max(vx * hx + ndv * hz, 0.0)
                ndl = 2 * vdh * hz - ndv
                if ndl <= 0:
                    continue
                # Cancel N.V analytically from Gvis: the N.V=0 endpoint is finite.
                visibility = (ndl / (ndl * (1 - k) + k)) * vdh / (hz * (ndv * (1 - k) + k))
                fresnel_bias = (1 - vdh) ** 5
                scale += (1 - fresnel_bias) * visibility
                bias += fresnel_bias * visibility
            for value in (scale / SAMPLES, bias / SAMPLES):
                table.append(struct.unpack("<H", struct.pack("<e", value))[0])
    lines = [
        "// Generated by tools/rendering/generate_environment_brdf.py; do not edit.",
        "// GGX/Schlick IBL, 2048 Hammersley samples/texel, RG16F, row-major A/B.",
        "// Columns: N.V=(x/63)^2. Rows: roughness=0.05+0.95*y/63.",
        "#pragma once", "", "#include <array>", "#include <cstdint>", "",
        "namespace Luminumbra::Rendering {",
        "inline constexpr int kEnvironmentBrdfLutSize = 64;",
        "// clang-format off",
        "inline constexpr std::array<std::uint16_t, 8192> kEnvironmentBrdfLut = {",
    ]
    for i in range(0, len(table), 12):
        lines.append("    " + ", ".join(f"0x{value:04x}" for value in table[i:i + 12]) + ",")
    lines.extend(["};", "// clang-format on", "} // namespace Luminumbra::Rendering", ""])
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify the checked-in table")
    args = parser.parse_args()
    result = generate()
    if args.check:
        if OUTPUT.read_text() != result:
            raise SystemExit(f"Generated environment BRDF is stale: {OUTPUT}")
        print("Environment BRDF table matches its generator")
    else:
        OUTPUT.write_text(result)
        print(f"Wrote {OUTPUT}")
