include_guard(GLOBAL)

set(LUMINUMBRA_ENGINE_VERSION "${PROJECT_VERSION}" CACHE STRING "Luminumbra engine version")
set(LUMINUMBRA_ENGINE_GIT_SHA "unknown")
set(LUMINUMBRA_ENGINE_IS_RELEASE_TAG OFF)

find_package(Git QUIET)
if(Git_FOUND)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
        WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        OUTPUT_VARIABLE LUMINUMBRA_ENGINE_GIT_SHA_RESULT
        RESULT_VARIABLE LUMINUMBRA_ENGINE_GIT_SHA_EXIT_CODE
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    if(LUMINUMBRA_ENGINE_GIT_SHA_EXIT_CODE EQUAL 0 AND NOT LUMINUMBRA_ENGINE_GIT_SHA_RESULT STREQUAL "")
        set(LUMINUMBRA_ENGINE_GIT_SHA "${LUMINUMBRA_ENGINE_GIT_SHA_RESULT}")
    endif()
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" describe --tags --exact-match --match "v${PROJECT_VERSION}"
        WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        RESULT_VARIABLE LUMINUMBRA_ENGINE_TAG_EXIT_CODE
        OUTPUT_QUIET
        ERROR_QUIET
    )
    if(LUMINUMBRA_ENGINE_TAG_EXIT_CODE EQUAL 0)
        set(LUMINUMBRA_ENGINE_IS_RELEASE_TAG ON)
    endif()
endif()

if(LUMINUMBRA_ENGINE_IS_RELEASE_TAG)
    set(LUMINUMBRA_ENGINE_VERSION_STRING "${LUMINUMBRA_ENGINE_VERSION}")
else()
    set(LUMINUMBRA_ENGINE_VERSION_STRING "${LUMINUMBRA_ENGINE_VERSION}+${LUMINUMBRA_ENGINE_GIT_SHA}")
endif()
set(LUMINUMBRA_ENGINE_VERSION_INCLUDE_DIR "${CMAKE_BINARY_DIR}/generated/luminumbra_common")
set(LUMINUMBRA_ENGINE_VERSION_HEADER "${LUMINUMBRA_ENGINE_VERSION_INCLUDE_DIR}/core/EngineVersion.h")

configure_file(
    "${CMAKE_SOURCE_DIR}/src/luminumbra_common/core/EngineVersion.h.in"
    "${LUMINUMBRA_ENGINE_VERSION_HEADER}"
    @ONLY
)
